spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 4423423794094@qq.com
    password: vloopjmhjsdffdeb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true